apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-server
  template:
    metadata:
      labels:
        app: ollama-server
    spec:
      containers:
      - name: ollama-server
        image: gcr.io/pivotal-keep-461818-j4/ollama-server:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: OLLAMA_MODEL
          value: "gemma:2b"
        - name: OLLAMA_NUM_PARALLEL
          value: "4"
        - name: OLLAMA_MAX_LOADED_MODELS
          value: "1"
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
            # If using GPU, request it here:
          limits:
            memory: "4Gi"
            cpu: "2"