apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-agent
  template:
    metadata:
      labels:
        app: ollama-agent
    spec:
      containers:
      - name: ollama
        image: gcr.io/pivotal-keep-461818-j4/ollama-server:latest
        ports:
        - containerPort: 8080
        env:
        - name: OLLAMA_MODEL
          value: "gemma:2b"
        - name: OLLAMA_NUM_PARALLEL
          value: "4"
        - name: OLLAMA_MAX_LOADED_MODELS
          value: "1"
        resources:
          requests:
            memory: "16Gi"
            cpu: "4"
            # If using GPU, request it here:
          limits:
            memory: "32Gi"
            cpu: "8"